tools:
  str_replace_editor:
    signature: |
      str_replace_editor <command> <path> [<file_text>] [<old_str>] [<new_str>] [<insert_line>]
    # This docstrings was taken from openhands:
    # https://github.com/All-Hands-AI/OpenHands/blob/main/openhands/agenthub/codeact_agent/function_calling.py
    docstring: >
      Custom editing tool for editing files
      * State is persistent across command calls and discussions with the user
      * If a `command` generates a long output, it will be truncated and marked with `<response clipped>`

      Notes for using the `str_replace` command:
      * The `old_str` parameter should match EXACTLY one or more consecutive lines from the original file. Be mindful of whitespaces!
      * If the `old_str` parameter is not unique in the file, the replacement will not be performed. Make sure to include enough context in `old_str` to make it unique
      * The `new_str` parameter should contain the edited lines that should replace the `old_str`
    arguments:
      - name: command
        type: string
        description: "The commands to run. Allowed options are: `str_replace`, `insert`"
        required: true
        enum: ["str_replace", "insert"]
      - name: path
        type: string
        description: "Absolute path to file or directory, e.g. `/testbed/file.py` or `/testbed`."
        required: true
      - name: file_text
        type: string
        description: "Required parameter of `create` command, with the content of the file to be created."
        required: false
        argument_format: "--file_text {{value}}"
      - name: old_str
        type: string
        description: "Required parameter of `str_replace` command containing the string in `path` to replace."
        required: false
        argument_format: "--old_str {{value}}"
      - name: new_str
        type: string
        description: "Optional parameter of `str_replace` command containing the new string (if not given, no string will be added). Required parameter of `insert` command containing the string to insert."
        required: false
        argument_format: "--new_str {{value}}"
      - name: insert_line
        type: integer
        description: "Required parameter of `insert` command. The `new_str` will be inserted AFTER the line `insert_line` of `path`."
        required: false
        argument_format: "--insert_line {{value}}"
state_command: "_state_anthropic"
